parser: "@typescript-eslint/parser"
plugins:
- "@typescript-eslint"
- prettier
env:
  browser: true
  es6: true
  node: true
extends:
- 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
  no-undef:
  - off
  "@typescript-eslint/no-unused-vars":
  - error
  indent:
  - off
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - double
  - avoidEscape: true
    allowTemplateLiterals: true
  semi:
  - error
  - always
