steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: node:11
  entrypoint: yarn
  args: ['install']
- name: node:11
  entrypoint: yarn
  args: ['build']
- name: node:11
  entrypoint: yarn
  args: ['cover', '-r', 'isolate']
- name: gcr.io/cloud-builders/gcloud
  args: ['builds', 'submit',  '--config',  './cloud-builders/chrome/cloudbuild.yaml', '.']
- name: 'gcr.io/$PROJECT_ID/ci-node-chrome'
  entrypoint: yarn
  args: ['test', '-r', 'headless chrome']
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: ['./codecov.sh']
  env:
  - 'CODECOV_TOKEN=35c27442-dc86-4fb0-9897-62a9bf00f19a'
images: ['gcr.io/$PROJECT_ID/ci-node-chrome:latest']