steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: node:11
  entrypoint: yarn
  args: ['install']
- name: node:11
  entrypoint: yarn
  args: ['build']
- name: node:11
  entrypoint: yarn
  args: ['run', 'cover']
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: ['./codecov.sh']
  env:
  - 'CODECOV_TOKEN=35c27442-dc86-4fb0-9897-62a9bf00f19a'
